# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreateLayerFromSelected
                                 A QGIS plugin
 Creates an in memory layer from currently selected feartures. Applies style from parent layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-08-12
        copyright            : (C) 2019 by Jeff Hamilton
        email                : info@easternspatial.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreateLayerFromSelected class from file CreateLayerFromSelected.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .create_from_selected import CreateLayerFromSelected
    return CreateLayerFromSelected(iface)
